/// Flutter icons PlusPrayer
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PlusPrayer
///      fonts:
///       - asset: fonts/PlusPrayer.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class PlusPrayer {
  PlusPrayer._();

  static const _kFontFam = 'PlusPrayer';
  static const String? _kFontPkg = null;

  static const IconData edit_prayer_list = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData praying_hands = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData praying_hands_outlined = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_prayer_list_2 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData praying_hands_locked = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData praying_hands_outlined_thin = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData praying_hands_outlined_thick = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_dots = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_dots_list = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pray = IconData(0xf683, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
